apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vllm.fullname" . }}-egress
  labels:
    {{- include "vllm.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vllm.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    - to:
        {{- range .Values.security.networkPolicyEgress }}
        - ipBlock:
            cidr: {{ . }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}

