apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: openshift-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: lvms-vg1
  resources:
    requests:
      storage: 1Gi

