apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nanabush-dev
resources:
  - ../../base
configMapGenerator:
  - name: vllm-config
    literals:
      - VLLM_LOG_LEVEL=info
patches:
  - target:
      kind: Namespace
      name: nanabush
    patch: |-
      - op: replace
        path: /metadata/name
        value: nanabush-dev

